language: haxe

os:
  - linux
  - osx

haxe:
  - development

sudo: false

before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
      chmod +x ./cc-test-reporter;
      ./cc-test-reporter before-build;
    fi

script:
  # test compilation/show errors
  - haxe extraParams.hxml --run haxevm.Main tests/samples/Main.hx
  # run the tests
  - haxe test.hxml
  # check compilation status on cpp
  - haxelib install hxcpp
  - haxe extraParams.hxml --main haxevm.Main -cpp build/cpp/
  - build/cpp/Main tests/samples/Main.hx
  # check compilation status on js
  - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs.git
  - haxe extraParams.hxml --main haxevm.Main -js build/haxevm.js -lib hxnodejs -D js-es=6
  - node build/haxevm.js tests/samples/Main.hx

after_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t lcov;
    fi
